In [53]:
import sklearn as sk
from sklearn import datasets

from sklearn.linear_model import LogisticRegression, Perceptron, LinearRegression, BayesianRidge
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVC, LinearSVC, SVR
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, CategoricalNB, ComplementNB

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

from matplotlib import pyplot as plt
import seaborn as sns

import numpy as np
from numpy.random import shuffle
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/koroteevmv/ML_course/2024/ML4.1%20metrics/heart.csv"
df = pd.read_csv(url)
X = df.drop("output", axis= 1)
y = df["output"]
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [5]:
log_test = LogisticRegression().fit(X, y)

D:\Conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [6]:
log_test.score(X, y)

0.8547854785478548

In [7]:
X_train, y_train = X[:200], y[:200]
X_test, y_test = X[200:], y[200:]

In [8]:
log_test = LogisticRegression().fit(X_train, y_train)

D:\Conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:
log_test.score(X_train, y_train), log_test.score(X_test, y_test)

(0.9, 0.5339805825242718)

In [10]:
N = int(X.shape[0] * 0.8)
X_train, y_train, X_test, y_test = X[:N], y[:N], X[N:], y[N:]

In [11]:
log_test = LogisticRegression().fit(X_train, y_train)

D:\Conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
log_test.score(X_train, y_train), log_test.score(X_test, y_test)

(0.8884297520661157, 0.6229508196721312)

In [13]:
df.tail()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0

In [14]:
mask = np.array([True] * N + [False] * (y.shape[0] - N))

In [15]:
shuffle(mask)
mask

array([ True,  True,  True, False, False,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False, False,  True,  True,
       False, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,

In [16]:
X_train, y_train, X_test, y_test = X[mask], y[mask], X[~mask], y[~mask]

In [17]:
log_test = LogisticRegression().fit(X_train, y_train)

D:\Conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
log_test.score(X_train, y_train), log_test.score(X_test, y_test)

(0.8429752066115702, 0.8852459016393442)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size= 0.8)

In [20]:
y_test_pred = log_test.predict(X_test)
y_train_pred = log_test.predict(X_train)

In [21]:
confusion_matrix(y_train, y_train_pred)

array([[ 83,  23],
       [ 11, 125]], dtype=int64)

In [22]:
confusion_matrix(y_test, y_test_pred)

array([[23,  9],
       [ 2, 27]], dtype=int64)

In [23]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.92      0.72      0.81        32
           1       0.75      0.93      0.83        29

    accuracy                           0.82        61
   macro avg       0.83      0.82      0.82        61
weighted avg       0.84      0.82      0.82        61



In [24]:
precision_score(y_test, y_test_pred)

0.75

In [25]:
def metrics_table(y_train, y_train_pred, y_test, y_test_pred):
    metrics = pd.DataFrame({
        "Train": [
            accuracy_score(y_train, y_train_pred),
            precision_score(y_train, y_train_pred),
            recall_score(y_train, y_train_pred),
            f1_score(y_train, y_train_pred),
        ],
        "Test": [
            accuracy_score(y_test, y_test_pred),
            precision_score(y_test, y_test_pred),
            recall_score(y_test, y_test_pred),
            f1_score(y_test, y_test_pred),
        ],
    }, index = ["Accuracy", "Precision", "Recall", "F1"])

    return metrics


def metrics_table_test(y_test, y_test_pred):
    metrics = pd.DataFrame({
        "Test": [
            accuracy_score(y_test, y_test_pred),
            precision_score(y_test, y_test_pred),
            recall_score(y_test, y_test_pred),
            f1_score(y_test, y_test_pred),
        ],
    }, index = ["Accuracy", "Precision", "Recall", "F1"])

    return metrics

metrics_table(y_train, y_train_pred, y_test, y_test_pred)

Train      Test
Accuracy   0.859504  0.819672
Precision  0.844595  0.750000
Recall     0.919118  0.931034
F1         0.880282  0.830769

1. Повторите анализ для других видов моделей. Используйте 5-10 разных классов моделей. Подсчитывайте только метрики на тестовой выборке.

In [26]:
perc_test = Perceptron().fit(X_train, y_train)
svcrbf_test = SVC(kernel= "rbf").fit(X_train, y_train)
linsvc_test = LinearSVC().fit(X_train, y_train)
mlp_test = MLPClassifier(hidden_layer_sizes=(8, 8, 8, 8, 8,)).fit(X_train, y_train)
tree_test = DecisionTreeClassifier().fit(X_train, y_train)
neig_test = KNeighborsClassifier().fit(X_train, y_train)
mult_test = MultinomialNB().fit(X_train, y_train)
bern_test = BernoulliNB().fit(X_train, y_train)
cat_test = CategoricalNB().fit(X_train, y_train)
comp_test = ComplementNB().fit(X_train, y_train)

D:\Conda\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
D:\Conda\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
D:\Conda\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Perceptron

In [27]:
y_test_pred = perc_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

D:\Conda\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Test
Accuracy   0.52459
Precision  0.00000
Recall     0.00000
F1         0.00000

SVC rbf (метод опорных векторов с гауссовым ядром)

In [31]:
y_test_pred = svcrbf_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

Test
Accuracy   0.557377
Precision  0.520000
Recall     0.896552
F1         0.658228

LinearSVC (метод опорных векторов с линейным ядром)

In [32]:
y_test_pred = linsvc_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

Test
Accuracy   0.803279
Precision  0.707317
Recall     1.000000
F1         0.828571

MLPClassifier (многослойный перцептрон)

In [33]:
y_test_pred = mlp_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

Test
Accuracy   0.704918
Precision  0.627907
Recall     0.931034
F1         0.750000

DecisionTreeClassifier (дерево решений)

In [34]:
y_test_pred = tree_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

Test
Accuracy   0.770492
Precision  0.702703
Recall     0.896552
F1         0.787879

KNeighborsClassifier (метод K ближайших соседей)

In [35]:
y_test_pred = neig_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

Test
Accuracy   0.672131
Precision  0.621622
Recall     0.793103
F1         0.696970

MultinomialNB (мультиномиальный наивный Байесс)

In [36]:
y_test_pred = mult_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

Test
Accuracy   0.688525
Precision  0.625000
Recall     0.862069
F1         0.724638

BernoulliNB (Бернули наивный Байесс)

In [37]:
y_test_pred = bern_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

Test
Accuracy   0.819672
Precision  0.781250
Recall     0.862069
F1         0.819672

CategorialNB (категориальный наивный Байесс)

In [38]:
y_test_pred = cat_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

Test
Accuracy   0.803279
Precision  0.717949
Recall     0.965517
F1         0.823529

ComplementNB (комплементарный наивный Байесс)

In [39]:
y_test_pred = comp_test.predict(X_test)
metrics_table_test(y_test, y_test_pred)

Test
Accuracy   0.688525
Precision  0.625000
Recall     0.862069
F1         0.724638

2. Повторите анализ для другого датасета по вашему выбору. Используйте несколько моделей для сравнения. Используйте датасет для множественной классификации.

In [40]:
iris = datasets.load_iris()
X = pd.DataFrame(iris["data"])
y = pd.DataFrame(iris["target"])
X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [42]:
y.head()

0
0  0
1  0
2  0
3  0
4  0

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size= 0.8)

In [44]:
tree_test = DecisionTreeClassifier().fit(X_train, y_train)
svc_test = SVC(kernel= "rbf").fit(X_train, y_train)
neig_test = KNeighborsClassifier().fit(X_train, y_train)

D:\Conda\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Conda\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


DecisionTreeClassifier (дерево решений)

In [45]:
y_test_pred = tree_test.predict(X_test)
accuracy_score(y_test, y_test_pred)

0.9666666666666667

SVC rbf (метод опорных векторов с гауссовым ядром)

In [46]:
y_test_pred = svc_test.predict(X_test)
accuracy_score(y_test, y_test_pred)

0.9333333333333333

KNeighborsClassifier (метод K ближайших соседей)

In [47]:
y_test_pred = neig_test.predict(X_test)
accuracy_score(y_test, y_test_pred)

0.9666666666666667

3. Повторите анализ для датасета, предназначенного для решения задачи регрессии. Используйте все метрики качества регрессии, изученные на лекции. Постройте 5 - 10 разных моделей регрессии.